//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nhaxuatban", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Nhaxuatban : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dienthoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int manxbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tennxbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dienthoai {
            get {
                return this.dienthoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.dienthoaiField, value) != true)) {
                    this.dienthoaiField = value;
                    this.RaisePropertyChanged("dienthoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int manxb {
            get {
                return this.manxbField;
            }
            set {
                if ((this.manxbField.Equals(value) != true)) {
                    this.manxbField = value;
                    this.RaisePropertyChanged("manxb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tennxb {
            get {
                return this.tennxbField;
            }
            set {
                if ((object.ReferenceEquals(this.tennxbField, value) != true)) {
                    this.tennxbField = value;
                    this.RaisePropertyChanged("tennxb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tacgia", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Tacgia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int matgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tentgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.gioitinhField, value) != true)) {
                    this.gioitinhField = value;
                    this.RaisePropertyChanged("gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int matg {
            get {
                return this.matgField;
            }
            set {
                if ((this.matgField.Equals(value) != true)) {
                    this.matgField = value;
                    this.RaisePropertyChanged("matg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tentg {
            get {
                return this.tentgField;
            }
            set {
                if ((object.ReferenceEquals(this.tentgField, value) != true)) {
                    this.tentgField = value;
                    this.RaisePropertyChanged("tentg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sach", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Sach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chungloaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dongiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int manxbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int matgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngayxbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tensachField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chungloai {
            get {
                return this.chungloaiField;
            }
            set {
                if ((object.ReferenceEquals(this.chungloaiField, value) != true)) {
                    this.chungloaiField = value;
                    this.RaisePropertyChanged("chungloai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dongia {
            get {
                return this.dongiaField;
            }
            set {
                if ((this.dongiaField.Equals(value) != true)) {
                    this.dongiaField = value;
                    this.RaisePropertyChanged("dongia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int manxb {
            get {
                return this.manxbField;
            }
            set {
                if ((this.manxbField.Equals(value) != true)) {
                    this.manxbField = value;
                    this.RaisePropertyChanged("manxb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int masach {
            get {
                return this.masachField;
            }
            set {
                if ((this.masachField.Equals(value) != true)) {
                    this.masachField = value;
                    this.RaisePropertyChanged("masach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int matg {
            get {
                return this.matgField;
            }
            set {
                if ((this.matgField.Equals(value) != true)) {
                    this.matgField = value;
                    this.RaisePropertyChanged("matg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngayxb {
            get {
                return this.ngayxbField;
            }
            set {
                if ((this.ngayxbField.Equals(value) != true)) {
                    this.ngayxbField = value;
                    this.RaisePropertyChanged("ngayxb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tensach {
            get {
                return this.tensachField;
            }
            set {
                if ((object.ReferenceEquals(this.tensachField, value) != true)) {
                    this.tensachField = value;
                    this.RaisePropertyChanged("tensach");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tennxbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tensachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tentgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tennxb {
            get {
                return this.tennxbField;
            }
            set {
                if ((object.ReferenceEquals(this.tennxbField, value) != true)) {
                    this.tennxbField = value;
                    this.RaisePropertyChanged("tennxb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tensach {
            get {
                return this.tensachField;
            }
            set {
                if ((object.ReferenceEquals(this.tensachField, value) != true)) {
                    this.tensachField = value;
                    this.RaisePropertyChanged("tensach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tentg {
            get {
                return this.tentgField;
            }
            set {
                if ((object.ReferenceEquals(this.tentgField, value) != true)) {
                    this.tentgField = value;
                    this.RaisePropertyChanged("tentg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadnxb", ReplyAction="http://tempuri.org/IService1/LoadnxbResponse")]
        WindowsFormsApp1.ServiceReference1.Nhaxuatban[] Loadnxb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadnxb", ReplyAction="http://tempuri.org/IService1/LoadnxbResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Nhaxuatban[]> LoadnxbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertnxb", ReplyAction="http://tempuri.org/IService1/InsertnxbResponse")]
        void Insertnxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertnxb", ReplyAction="http://tempuri.org/IService1/InsertnxbResponse")]
        System.Threading.Tasks.Task InsertnxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatenxb", ReplyAction="http://tempuri.org/IService1/UpdatenxbResponse")]
        void Updatenxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatenxb", ReplyAction="http://tempuri.org/IService1/UpdatenxbResponse")]
        System.Threading.Tasks.Task UpdatenxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletenxb", ReplyAction="http://tempuri.org/IService1/DeletenxbResponse")]
        void Deletenxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletenxb", ReplyAction="http://tempuri.org/IService1/DeletenxbResponse")]
        System.Threading.Tasks.Task DeletenxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadtg", ReplyAction="http://tempuri.org/IService1/LoadtgResponse")]
        WindowsFormsApp1.ServiceReference1.Tacgia[] Loadtg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadtg", ReplyAction="http://tempuri.org/IService1/LoadtgResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Tacgia[]> LoadtgAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserttg", ReplyAction="http://tempuri.org/IService1/InserttgResponse")]
        void Inserttg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Inserttg", ReplyAction="http://tempuri.org/IService1/InserttgResponse")]
        System.Threading.Tasks.Task InserttgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatetg", ReplyAction="http://tempuri.org/IService1/UpdatetgResponse")]
        void Updatetg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatetg", ReplyAction="http://tempuri.org/IService1/UpdatetgResponse")]
        System.Threading.Tasks.Task UpdatetgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletetg", ReplyAction="http://tempuri.org/IService1/DeletetgResponse")]
        void Deletetg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletetg", ReplyAction="http://tempuri.org/IService1/DeletetgResponse")]
        System.Threading.Tasks.Task DeletetgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadsach", ReplyAction="http://tempuri.org/IService1/LoadsachResponse")]
        WindowsFormsApp1.ServiceReference1.Sach[] Loadsach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loadsach", ReplyAction="http://tempuri.org/IService1/LoadsachResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Sach[]> LoadsachAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertsach", ReplyAction="http://tempuri.org/IService1/InsertsachResponse")]
        void Insertsach(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertsach", ReplyAction="http://tempuri.org/IService1/InsertsachResponse")]
        System.Threading.Tasks.Task InsertsachAsync(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatesach", ReplyAction="http://tempuri.org/IService1/UpdatesachResponse")]
        void Updatesach(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatesach", ReplyAction="http://tempuri.org/IService1/UpdatesachResponse")]
        System.Threading.Tasks.Task UpdatesachAsync(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletesach", ReplyAction="http://tempuri.org/IService1/DeletesachResponse")]
        void Deletesach(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deletesach", ReplyAction="http://tempuri.org/IService1/DeletesachResponse")]
        System.Threading.Tasks.Task DeletesachAsync(WindowsFormsApp1.ServiceReference1.Sach sach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data", ReplyAction="http://tempuri.org/IService1/dataResponse")]
        WindowsFormsApp1.ServiceReference1.Report[] data(string Tentg, string Tennxb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data", ReplyAction="http://tempuri.org/IService1/dataResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Report[]> dataAsync(string Tentg, string Tennxb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.Nhaxuatban[] Loadnxb() {
            return base.Channel.Loadnxb();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Nhaxuatban[]> LoadnxbAsync() {
            return base.Channel.LoadnxbAsync();
        }
        
        public void Insertnxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            base.Channel.Insertnxb(nxb);
        }
        
        public System.Threading.Tasks.Task InsertnxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            return base.Channel.InsertnxbAsync(nxb);
        }
        
        public void Updatenxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            base.Channel.Updatenxb(nxb);
        }
        
        public System.Threading.Tasks.Task UpdatenxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            return base.Channel.UpdatenxbAsync(nxb);
        }
        
        public void Deletenxb(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            base.Channel.Deletenxb(nxb);
        }
        
        public System.Threading.Tasks.Task DeletenxbAsync(WindowsFormsApp1.ServiceReference1.Nhaxuatban nxb) {
            return base.Channel.DeletenxbAsync(nxb);
        }
        
        public WindowsFormsApp1.ServiceReference1.Tacgia[] Loadtg() {
            return base.Channel.Loadtg();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Tacgia[]> LoadtgAsync() {
            return base.Channel.LoadtgAsync();
        }
        
        public void Inserttg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            base.Channel.Inserttg(tacgia);
        }
        
        public System.Threading.Tasks.Task InserttgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            return base.Channel.InserttgAsync(tacgia);
        }
        
        public void Updatetg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            base.Channel.Updatetg(tacgia);
        }
        
        public System.Threading.Tasks.Task UpdatetgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            return base.Channel.UpdatetgAsync(tacgia);
        }
        
        public void Deletetg(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            base.Channel.Deletetg(tacgia);
        }
        
        public System.Threading.Tasks.Task DeletetgAsync(WindowsFormsApp1.ServiceReference1.Tacgia tacgia) {
            return base.Channel.DeletetgAsync(tacgia);
        }
        
        public WindowsFormsApp1.ServiceReference1.Sach[] Loadsach() {
            return base.Channel.Loadsach();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Sach[]> LoadsachAsync() {
            return base.Channel.LoadsachAsync();
        }
        
        public void Insertsach(WindowsFormsApp1.ServiceReference1.Sach sach) {
            base.Channel.Insertsach(sach);
        }
        
        public System.Threading.Tasks.Task InsertsachAsync(WindowsFormsApp1.ServiceReference1.Sach sach) {
            return base.Channel.InsertsachAsync(sach);
        }
        
        public void Updatesach(WindowsFormsApp1.ServiceReference1.Sach sach) {
            base.Channel.Updatesach(sach);
        }
        
        public System.Threading.Tasks.Task UpdatesachAsync(WindowsFormsApp1.ServiceReference1.Sach sach) {
            return base.Channel.UpdatesachAsync(sach);
        }
        
        public void Deletesach(WindowsFormsApp1.ServiceReference1.Sach sach) {
            base.Channel.Deletesach(sach);
        }
        
        public System.Threading.Tasks.Task DeletesachAsync(WindowsFormsApp1.ServiceReference1.Sach sach) {
            return base.Channel.DeletesachAsync(sach);
        }
        
        public WindowsFormsApp1.ServiceReference1.Report[] data(string Tentg, string Tennxb) {
            return base.Channel.data(Tentg, Tennxb);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Report[]> dataAsync(string Tentg, string Tennxb) {
            return base.Channel.dataAsync(Tentg, Tennxb);
        }
    }
}
